name: shinx_dev
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
  eco:
    git: https://github.com/Francessco121/eco.git
  sass_builder: ^2.2.1
  shelf_proxy: ^1.0.4

dependency_overrides:
  eco:
    path: ../../eco/eco